### ISSUE TITLE
Cerebellum bug in linux

### ISSUE THREAD

**Issue by snino64** [lantonov/asmFish#12] opened 2016-12-21 22:03 UTC
Cerebellum: The linux version has a bug.

./pedantFishL_2016-12-17_base
pedantFishL_2016-12-17_base
brain2polyglot depth 200 in "Cerebellum_light.bin" out "polybook.bin"
sys_write failed rax: 0xfffffffffffffff2

Thanks

**Comment by lantonov** [comment] 2016-12-22 06:43
Interesting. I don't have access to Linux at the moment but will try it tonight on Ubuntu Bash for Windows

**Comment by lantonov** [comment] 2016-12-22 20:59
Starting all of asm/pedant fishes in Ubuntu bash for Windows gives the following error:
`sys_mmap failed rax: 0xffffffffffffffa1`
I compiled them in bash with the Linux compiler fasm.x64 but again this error message. Further, the versions compiled by Moha of 2016-11-04 also give the same error. Probably the problem is in the code and not in the compiler.
I do not have a true Linux computer and would like to know if these compiles work in Linux.

**Comment by snino64** [comment] 2016-12-22 22:40
Those builds work fine on linux. I only have the problem building the book cerebellum.
The tests I do with asmfish compilations work correctly. Also, they work on both scidvspc and chessx.
The processor I use is i7 950.
Tomorrow I try to test it on an amd fx 8350 processor if I have time.
thanks for your nice works
 (Ubuntu 16.04 and Ubuntu 14.04) 

      De: Lyudmil Antonov <notifications@github.com>
 Para: lantonov/asmFish <asmFish@noreply.github.com> 
CC: snino64 <snino64@yahoo.es>; Author <author@noreply.github.com>
 Enviado: Jueves 22 de diciembre de 2016 20:59
 Asunto: Re: [lantonov/asmFish] Cerebellum bug in linux (#12)
   
Starting all of asm/pedant fishes in Ubuntu bash for Windows gives the following error:
sys_mmap failed rax: 0xffffffffffffffa1
I compiled them in bash with the Linux compiler fasm.x64 but again this error message. Further, the versions compiled by Moha of 2016-11-04 also give the same error. Probably the problem is in the code and not in the compiler.
I do not have a true Linux computer and would like to know if these compiles work in Linux.

**Comment by lantonov** [comment] 2016-12-23 07:01
It's a relief to know that the Linux versions actually work in Linux. The Cerebellum version is far more manageable problem. I will compile several versions of asm/pedant for Linux and put them in the Cerebellum folder for you to try. Then we shall select the best working one and discard the rest.

Cerebellum book can be made with any version which has flag USE_BOOK set (`USE_BOOK equ 1`). The problem is that the default book is limited to 50 plies (25 moves). To increase that, some constants deeper in the code should be increased. This may be the cause of the present issue.

As I see, you have tried pedantFishL_2016-12-17_base. The unmodified pedantFish cannot reach 200 plies. Have you tried the Linux binary that is in the Cerebellum folder (Cerebellum2polyglot_Linux) ?

**Comment by snino64** [comment] 2016-12-23 15:16
Today compile the base and popcnt versions of asmfish and pedantfish and continue with the same error (correcting the corresponding asm file book = 1)If I watch any version that works, I'll let you know.

      De: Lyudmil Antonov <notifications@github.com>
 Para: lantonov/asmFish <asmFish@noreply.github.com> 
CC: snino64 <snino64@yahoo.es>; Author <author@noreply.github.com>
 Enviado: Viernes 23 de diciembre de 2016 7:01
 Asunto: Re: [lantonov/asmFish] Cerebellum bug in linux (#12)
   
It's a relief to know that the Linux versions actually work in Linux. The Cerebellum version is far more manageable problem. I will compile several versions of asm/pedant for Linux and put them in the Cerebellum folder for you to try. Then we shall select the best working one and discard the rest.—

**Comment by lantonov** [comment] 2016-12-23 15:45
I suggest you try the binary Cerebellum2polyglot_Linux first and then the command
`brain2polyglot in "Cerebellum_Light.bin" out "polybook.bin" `
(without the depth limitation)
Make sure that the binary and Cerebellum are in the same folder.

**Comment by snino64** [comment] 2016-12-23 16:19
The folder is deleted.I use the 2016/11/12 version and notice the next error:

$ ./Cerebellum2polyglot_LinuxpedantFishL_2016-12-08_popcnt
brain2polyglot depth 1024 in "Cerebellum_light.bin" out "polybook.bin"
sys_write failed rax: 0xfffffffffffffff2

      De: Lyudmil Antonov <notifications@github.com>
 Para: lantonov/asmFish <asmFish@noreply.github.com> 
CC: snino64 <snino64@yahoo.es>; Author <author@noreply.github.com>
 Enviado: Viernes 23 de diciembre de 2016 15:45
 Asunto: Re: [lantonov/asmFish] Cerebellum bug in linux (#12)
   
I suggest you try the binary Cerebellum2polyglot_Linux first and then the command
brain2polyglot in "Cerebellum_Light.bin" out "polybook.bin"
(without the depth limitation)
Make sure that the binary and Cerebellum are in the same folder.—

**Comment by lantonov** [comment] 2016-12-23 16:20
./Cerebellum2polyglot_LinuxpedantFishL_2016-12-08_popcnt ?

The Cerebellum folder was moved here:
https://github.com/lantonov/asmFish/tree/executables

**Comment by snino64** [comment] 2016-12-23 20:28
2016-12-10 pocnt


      De: Lyudmil Antonov <notifications@github.com>
 Para: lantonov/asmFish <asmFish@noreply.github.com> 
CC: snino64 <snino64@yahoo.es>; Author <author@noreply.github.com>
 Enviado: Viernes 23 de diciembre de 2016 16:20
 Asunto: Re: [lantonov/asmFish] Cerebellum bug in linux (#12)
   
./Cerebellum2polyglot_LinuxpedantFishL_2016-12-08_popcnt ?—

**Comment by snino64** [comment] 2016-12-24 12:39
This version works correctly. It is not important for me to put a limit to the depth, although it would be interesting.
New versions have that bug, but I can use the older version.

**Comment by lantonov** [comment] 2016-12-24 12:43
Which version? That in the Cerebellum folder or 2016-12-10 popcnt?

**Comment by snino64** [comment] 2016-12-24 20:10
I'm surprised: Now the last version works and the one of the 2016-12-10 day fails me.
I have compiled the latest version of 2016-12-22 and it works.
I send you the compile.
I will compile it and try again more often.

**Comment by snino64** [comment] 2016-12-24 20:11
$ ./CerebellumPedantFishL_2016-12-24_popcnt
pedantFishL_2016-12-24_popcnt
brain2polyglot in "Cerebellum_Light.bin" out "polybook.bin"
brain entries: 5047190
brain duplicates (HMM): 0
brain unsorted (OK): 0
starting search with maxDepth 50
0 of 5047190 entries found  searching NONE 
65536 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
131072 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
196608 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
262144 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
327680 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
393216 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
458752 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
524288 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
589824 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
655360 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
720896 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
786432 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
851968 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
917504 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
983040 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
1048576 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 
1114112 of 5047190 entries found  searching e2e4 e7e5 g1f3 b8c6 b1c3 g8f6 
1179648 of 5047190 entries found  searching e2e4 e7e5 g1f3 d7d6 b1c3 g7g6 
1245184 of 5047190 entries found  searching e2e4 e7e5 g2g3 c7c5 f1g2 g8f6 
1310720 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1376256 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1441792 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1507328 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1572864 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1638400 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1703936 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1769472 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1835008 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 
1900544 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 d2d4 g7g6 
1966080 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 b1c3 b8c6 
2031616 of 5047190 entries found  searching e2e4 c7c5 g1f3 d7d6 f1b5 b8c6 
2097152 of 5047190 entries found  searching e2e4 c7c5 g1f3 b7b6 d2d4 e7e6 
2162688 of 5047190 entries found  searching e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 
2228224 of 5047190 entries found  searching e2e4 b7b6 d2d4 d7d5 b1c3 e7e6 
2293760 of 5047190 entries found  searching e2e4 c7c6 d2d4 d7d5 b1c3 d5e4 
2359296 of 5047190 entries found  searching e2e4 c7c6 d2d4 d7d5 b1c3 h7h6 
2424832 of 5047190 entries found  searching e2e4 c7c6 d2d4 d7d5 c2c4 d5c4 
2490368 of 5047190 entries found  searching e2e4 c7c6 d2d4 d7d5 e4d5 c6d5 
2555904 of 5047190 entries found  searching e2e4 d7d5 e4d5 d8d5 b1c3 d5d8 
2621440 of 5047190 entries found  searching e2e4 d7d5 b1c3 e7e6 b2b3 g8f6 
2686976 of 5047190 entries found  searching e2e4 d7d6 g1f3 g7g6 c2c4 g8f6 
2752512 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
2818048 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
2883584 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
2949120 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
3014656 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
3080192 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
3145728 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
3211264 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
3276800 of 5047190 entries found  searching d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 
3342336 of 5047190 entries found  searching d2d4 d7d5 c2c4 c7c5 b1c3 g8f6 
3407872 of 5047190 entries found  searching d2d4 d7d5 c2c4 c7c6 g1f3 g8f6 
3473408 of 5047190 entries found  searching d2d4 d7d5 g1f3 g8f6 b1a3 c7c6 
3538944 of 5047190 entries found  searching d2d4 d7d5 g1f3 g8f6 c1e3 e7e6 
3604480 of 5047190 entries found  searching d2d4 g8f6 c2c4 e7e6 g1f3 f6g8 
3670016 of 5047190 entries found  searching d2d4 g8f6 c2c4 e7e6 g1f3 f6g8 
3735552 of 5047190 entries found  searching d2d4 g8f6 c2c4 c7c5 b1c3 g7g6 
3801088 of 5047190 entries found  searching d2d4 g8f6 g1f3 c7c5 b1c3 c5d4 
3866624 of 5047190 entries found  searching g1f3 d7d5 b2b3 g8f6 e2e3 c7c6 
3932160 of 5047190 entries found  searching g1f3 d7d5 c2c4 g8f6 c4d5 f6d5 
3997696 of 5047190 entries found  searching g1f3 e7e5 c2c4 b8c6 b1c3 f8c5 
BookSearch done
4042005 of 5047190 entries found
depth 50 line: e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 d2d3 f8c5 c2c3 d7d6 e1g1 e8g8 h2h3 a7a5 f1e1 c5b6 a2a4 h7h6 b1d2 c8e6 c4b5 c6a7 d2f1 b6c5 f1g3 a7b5 a4b5 f8e8 d3d4 e5d4 c3d4 c5b4 c1d2 b4d2 d1d2 d6d5 e4e5 f6e4 g3e4 d5e4 e1e4 d8d5 d2e2 b7b6 f3d2 e6d7 d2b1 d5b5 e2d2 d7f5 
sorting polyglot keys
done sorting polyglot keys
polyglot entries: 4042006
polyglot duplicates (OK): 0
polyglot unsorted (BAD): 0

**Comment by lantonov** [comment] 2016-12-24 20:16
Perfect !
Then I close this issue.
Happy Christmas! (or Hannukka, or Ramadan, or whatever you believe in)

**Closed as completed by lantonov** 2016-12-24 20:16 UTC
Labels: help wanted

**Comment by snino64** [comment] 2016-12-24 21:28
Happy Christmas
